/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioWaveformVisualizer: typeof import('./src/components/AudioWaveformVisualizer.vue')['default']
    BatchActionBar: typeof import('./src/components/BatchActionBar.vue')['default']
    BpmEditModal: typeof import('./src/components/BpmEditModal.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GridConfigPanel: typeof import('./src/components/GridConfigPanel.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    NoteEditorHeader: typeof import('./src/components/NoteEditorHeader.vue')['default']
    Obstacle: typeof import('./src/components/Obstacle.vue')['default']
    ObstacleConfig: typeof import('./src/components/ObstacleConfig.vue')['default']
    ObstacleSelector: typeof import('./src/components/ObstacleSelector.vue')['default']
    RhythmCanvas: typeof import('./src/components/RhythmCanvas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutKeyTip: typeof import('./src/components/ShortcutKeyTip.vue')['default']
    SongInfoPanel: typeof import('./src/components/SongInfoPanel.vue')['default']
    SongMetaCard: typeof import('./src/components/SongMetaCard.vue')['default']
    SongVisualization: typeof import('./src/components/SongVisualization.vue')['default']
    TrackManagerPopover: typeof import('./src/components/TrackManagerPopover.vue')['default']
    ViewportConfig: typeof import('./src/components/ViewportConfig.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
