/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BpmEditModal: typeof import('./src/components/BpmEditModal.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GridConfigPanel: typeof import('./src/components/GridConfigPanel.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    Obstacle: typeof import('./src/components/Obstacle.vue')['default']
    ObstacleConfig: typeof import('./src/components/ObstacleConfig.vue')['default']
    ObstacleSelector: typeof import('./src/components/ObstacleSelector.vue')['default']
    RhythmCanvas: typeof import('./src/components/RhythmCanvas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongInfoPanel: typeof import('./src/components/SongInfoPanel.vue')['default']
    SongMetaCard: typeof import('./src/components/SongMetaCard.vue')['default']
    ViewportConfig: typeof import('./src/components/ViewportConfig.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
